# Generated by Django 3.0.5 on 2022-06-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220426_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='api_key',
            new_name='huobi_api_key',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='margin_account_id',
            new_name='huobi_margin_account_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='secret_key',
            new_name='huobi_secret_key',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='spot_account_id',
            new_name='huobi_spot_account_id',
        ),
    ]
