# Generated by Django 3.0.5 on 2022-06-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220614_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ftx_huobi_secret_key',
            new_name='ftx_secret_key',
        ),
    ]
