# Generated by Django 3.0.5 on 2022-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220614_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ftx_sub_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
