# Generated by Django 3.0.5 on 2022-08-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_ftx_sub_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filled_audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='filled_audio_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='new_order_audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='new_order_audio_active',
            field=models.BooleanField(default=True),
        ),
    ]
