# Generated by Django 3.0.5 on 2022-08-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220815_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='filled_audio',
            new_name='buy_filled_audio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='new_order_audio',
            new_name='buy_new_order_audio',
        ),
        migrations.AddField(
            model_name='user',
            name='sell_filled_audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='sell_new_order_audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
