# Generated by Django 3.0.5 on 2022-03-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_trade_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='iceberg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='icebergs_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
