# Generated by Django 3.0.5 on 2022-03-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220319_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='completed_icebergs',
            field=models.IntegerField(default=0),
        ),
    ]
