# Generated by Django 3.0.5 on 2022-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_trade_completed_icebergs'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='market_making',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='market_making_array',
            field=models.TextField(default=''),
        ),
    ]
