# Generated by Django 3.0.5 on 2022-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220319_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='chase_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='chase_bot_duration',
            field=models.IntegerField(default=0),
        ),
    ]
