# Generated by Django 3.0.5 on 2022-03-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220319_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='chase_bot_completed_trades',
            field=models.IntegerField(default=0),
        ),
    ]
