# Generated by Django 3.0.5 on 2022-05-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220514_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='stop_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
