# Generated by Django 3.0.5 on 2022-05-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20220524_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='ladder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='ladder_end_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='ladder_start_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='ladder_trades_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='LadderTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('stop_loss', models.IntegerField()),
                ('take_profit', models.IntegerField()),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_trades', to='main.Trade')),
            ],
        ),
    ]
