# Generated by Django 3.0.5 on 2022-05-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20220529_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='laddertrade',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laddertrade',
            name='is_limit_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laddertrade',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laddertrade',
            name='price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laddertrade',
            name='stop_loss_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laddertrade',
            name='take_profit_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
