# Generated by Django 3.0.5 on 2022-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220530_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='ladder_order_ids',
            field=models.TextField(default='[]'),
        ),
    ]
