# Generated by Django 3.0.5 on 2022-05-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_trade_ladder_order_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='ladder_completed_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='ladder_prices_sum',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
