# Generated by Django 3.0.5 on 2022-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20220610_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='exchange',
            field=models.CharField(choices=[('huobi', 'Huobi'), ('ftx', 'FTX')], default='huobi', max_length=255),
            preserve_default=False,
        ),
    ]
