# Generated by Django 3.0.5 on 2022-06-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_trade_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolsetting',
            name='exchange',
            field=models.CharField(choices=[('huobi', 'Huobi'), ('ftx', 'FTX')], default='huobi', max_length=255),
            preserve_default=False,
        ),
    ]
