# Generated by Django 3.0.5 on 2022-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_symbolsetting_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laddertrade',
            name='price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='symbolsetting',
            name='min_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
