# Generated by Django 3.0.5 on 2022-07-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_trade_chase_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='post_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='reduce_only',
            field=models.BooleanField(default=False),
        ),
    ]
