# Generated by Django 3.0.5 on 2022-07-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_trade_hft_orders_check_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='hft_all_orders',
            field=models.TextField(default='[]'),
        ),
    ]
