# Generated by Django 3.0.5 on 2022-07-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_trade_hft_all_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'verbose_name': 'Trade', 'verbose_name_plural': 'Trades'},
        ),
    ]
