# Generated by Django 3.0.5 on 2022-07-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20220716_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='hft_all_orders',
        ),
    ]
