# Generated by Django 3.0.5 on 2022-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_trade_hft_all_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
